[project]
name = "ipinfo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "geoip2>=5.0.1",
    "pydantic>=2.11.3",
    "slowapi>=0.1.9",
    "user-agents>=2.2.0",
    "uvicorn>=0.34.2",
]
